@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/latest/C4_Context.puml

Person(user, "Пользователь", "Пользователь трекера задач")
System(taskTrackerSystem, "Трекер задач")

Rel(user, taskTrackerSystem, "Использует")

@enduml